### ISSUE TITLE
Annotate replicated objects indicating they are a replica and the source

### ISSUE THREAD

**Issue by cuotos** [appscode/kubed#112]
There is currently very little to identify that a secret or cm has been replicated from an original.

An annotation indicating that "this is a replication" and details of the source object would be handy.

**Comment by tamalsaha** [comment]
This is needed for #111

**Comment by tamalsaha** [comment]
![omni-origin](https://user-images.githubusercontent.com/94814/30855901-683f8374-a26b-11e7-8331-26e3bf4b8186.png)
