### ISSUE TITLE
Installing kubed fails due to missing service account

### ISSUE THREAD

**Issue by smifun** [appscode/kubed#121]
I follow install instructions using version 0.2.0 with rbac. (https://raw.githubusercontent.com/appscode/kubed/0.2.0/hack/deploy/with-rbac.yaml)
ReplicaSets events shows error 
```
Error creating: pods "kubed-operator-3023504165-" is forbidden: service account kube-system/kubed was not found, retry after the service account is created
```
Yaml file has resource description for kubed-operator serviceaccount which is created succesfully but apparently deployment is expecting service account to be named:
`
serviceAccountName: kubed
`

I'm using kubernetes
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T19:32:12Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sadlil** [comment]
This is probably a doc update issue. Can you change the deployment spec to use `kubed-operator` service account, see that works.

**Comment by tamalsaha** [comment]
Thanks @smifun ! It should be fixed now.
