### ISSUE TITLE
s3 snapshotter try to list all buckets

### ISSUE THREAD

**Issue by mbugeia** [appscode/kubed#133]
At start, the s3 snapshotter try to run this operation "osm ls --osmconfig /tmp/osm/config.yaml", which in my case result in a 403 because my IAM user only have right on one bucket. I don't see why it's necessary to list all the account buckets. 

Moreover, the region is hardcoded to "us-east-1" in the operator, that mean "osm ls "mybucket" --osmconfig /tmp/osm/config.yaml" will fail if the bucket is in a different region.

**Comment by tamalsaha** [comment]
Hi,
The goal was to verify that the given credentials are valid so that user can check that quickly. I have removed the check.
