### ISSUE TITLE
Keep backup of deleted or updated objects

### ISSUE THREAD

**Issue by tamalsaha** [appscode/kubed#16]
Also, optionally notify cluster admin if critical components are deleted.

https://github.com/appscode/go-notify

**Comment by TamalSaha** [comment]
-- backup-dir={PV-mounted-dir}

`/{backup-dir}/apis/extensions/v1beta1/namespaces/default/deployments/aphlictserver/{uid}.yaml`

**Comment by tamalsaha** [comment]
We can also take full backups periodically
