### ISSUE TITLE
invalid header field value error when setting up with S3.

### ISSUE THREAD

**Issue by kishorekumark** [appscode/kubed#161]
HI,
I'm not able to deploy kubed in my environment, getting following error.

I1215 17:09:05.915055       1 run.go:39] Starting kubed...
I1215 17:09:05.915149       1 run.go:57] configurations provided for kubed {  /srv/kubed/config.yaml :8080 :56790 false /tmp kube-system 5m0s}
W1215 17:09:05.915183       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1215 17:09:05.916254       1 run.go:85] Running kubed watcher
[golang-sh]$ osm lc --osmconfig /tmp/osm/config.yaml
Containers, listing the buckets: RequestError: send request failed
caused by: Get https://s3.amazonaws.com/: net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=XXXXXXX\n/20171215/us-east-1us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=YYYYYYY" for key Authorization
F1215 17:09:06.281528       1 operator.go:403] exit status 1

could you please help me how can i overcome this error?

**Comment by tamalsaha** [comment]
Which version of kubed are you using? Can you share the relevant portion of your config.yaml ?

**Comment by kishorekumark** [comment]
apiServer:
  address: :8080
  enableReverseIndex: true
  enableSearchIndex: true
clusterName: us-east
enableConfigSyncer: true
snapshotter:
  s3:
    endpoint: 's3.amazonaws.com'
    bucket: us-east-backup-kubed
    prefix: useast1-k8s
  storageSecretName: snap-secret
  sanitize: true
  schedule: '@every 1h'

**Comment by tamalsaha** [comment]
Should be fixed by https://github.com/appscode/kubed/releases/tag/0.7.0-rc.0 release. Please reopen if you are still having this issue.
