### ISSUE TITLE
List and delete all old indices matching prefix

### ISSUE THREAD

**Issue by tamalsaha** [appscode/kubed#177]
Currently we only look back 7 days for old indices. We should look back at all indices for this. This is important when user enables kubed janitor for first time.

https://github.com/appscode/kubed/blob/0a29193868fcce22a1fd1c64c73340608fe94191/pkg/elasticsearch/janitor.go#L73

**Comment by aerokite** [comment]
And when will you stop searching for logs to delete?

**Comment by tamalsaha** [comment]
fixed https://github.com/appscode/kubed/pull/179
