### ISSUE TITLE
How to properly restore snapshot

### ISSUE THREAD

**Issue by r-moiseev** [appscode/kubed#303]
How to properly restore snapshot created with kubed?

**Comment by hossainemruz** [comment]
@r-moiseev currently kubed does not provide any automatic restore facility from snapshot. You have to do it manually.

First, extract the snapshot `.tar.gz` file and you will get backed up yaml files. Then manually create the resources from the yaml files.

If you want automatic restore feature for kubed, please do a feature request. Also share your idea how you would like to restore. We will consider this future release.

**Comment by tamalsaha** [comment]
This is out of scope.
