### ISSUE TITLE
helm deployment doesn't use pre-existing kubed secret

### ISSUE THREAD

**Issue by gorzek** [appscode/kubed#312]
I attempted to the follow the guide for synchronizing configuration across clusters: https://appscode.com/products/kubed/0.8.0/guides/config-syncer/inter-cluster/

Installing kubed with helm, I noticed that it complained of being unable to find the contexts I specified for synchronization. It appeared that kubed was not using the pre-existing secret I configured per the tutorial, but instead created a new one (called kubed-kubed). When I replaced that secret with the same contents as my pre-existing secret, kubed worked fine.

Either I am doing something wrong, the documentation is outdated, or the helm chart is not configured to use a pre-existing secret for the kubed configuration.

Please advise.

**Comment by pirtoo** [comment]
My solution for this issue is to be able to add a config section directly in the helm chart to add whatever is needed: https://github.com/appscode/kubed/pull/333

**Comment by tamalsaha** [comment]
This has been fixed in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0
