### ISSUE TITLE
Forward Events to Elasticsearch

### ISSUE THREAD

**Issue by galexrt** [appscode/kubed#330]
Currently it is not possible to forward Kubernetes Events to Elasticsearch.
It would be good to see a new forwarding "channel" to Elasticsearch.

Features for Elasticsearch integration:

- [ ] All Events into one indice.
- [ ] Per namespace Elasticsearch indice for Events.
- [ ] Elasticsearch with and without authentication.

***

I'll probably take a stab at this for at least the general functionality.

**Comment by tamalsaha** [comment]
We have removed the event forwarder in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0. Closing.
