### ISSUE TITLE
Performance optimizing syncer

### ISSUE THREAD

**Issue by kespinola** [appscode/kubed#335]
We've been using the syncer functionality of kubed at my company for the last 3 weeks. We leverage Kuberenetes to offer on-demand staging environments for our qa team. Each of the staging environments we bring up is in its own namespace. The syncer feature of kubed is helping us bring over relevant configuration resources into the newly created namespace.

Yesterday we were experiencing some lag in copying over configurations into the namespaces. We had 200 namespaces being watched with 25 configurations files being copied into each namespace.

Is there any optimization recommendation you all can offer? Or if there is an area that could use some tuning we'd be happy to make a contribution to the project.

**Comment by tamalsaha** [comment]
Hey, sorry for very delayed response. If you still using kubed and have ideas to improve it, please send a pr.
