### ISSUE TITLE
Don't regenerate a certificate authority and a certificate everytime you deploy the helm chart

### ISSUE THREAD

**Issue by kurlzor** [appscode/kubed#346]
The helm chart regenerates a ca/certificate every time you deploy it. We use terraform based infra as code tools to manage our helm charts, and applying a plan with no modification still tries to replace kubed secrets because of this oversight.
Could you at least give the option to specify your own certificate ?

Thanks

**Comment by tamalsaha** [comment]
Dup https://github.com/appscode/kubed/issues/371

**Comment by tamalsaha** [comment]
Feel free to send a pr to fix that. I have commented how this is done in one of our chart. https://github.com/appscode/kubed/issues/371#issuecomment-573090718
