### ISSUE TITLE
kubed is messing up api-resources

### ISSUE THREAD

**Issue by loomsen** [appscode/kubed#351]
After kubed installation, I cannot run `kubectl api-resources` anymore.

Kubed itself seems to work fine and sync my secrets. But it messes up something in my clusters.

```

$ k logs -n kube-system kubed-kubed-5d54bcf7b5-5hfqm
[...]
E0429 21:37:19.567281       1 restmapper.go:117] Skipping failed API Groups: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
[...]

$ k api-resources 
error: unable to retrieve the complete list of server APIs: kubed.appscode.com/v1alpha1: the server is currently unable to handle the request
```

I think this is related to #316 which should be reopened as well.

**Comment by elisiano** [comment]
I'm seeing this too but only on one cluster. same version on other clusters works fine.
I tried to delete the deployment but the problem persist.
Did you manage to fix/work-around that?

**Comment by donifer** [comment]
Having the same issue, any workarounds?

**Comment by loomsen** [comment]
I'm disabling the apiserver upon installation...

**Comment by yoanisgil** [comment]
I'm also disabling `apiserver` during installation, which doesn't seem to pose a problem for the purpose of my use case (syncing secrets). 

@tamalsaha can you please share with us what would be the impact of disabling `apiserver` ? I'm trying to read through the docs to see how is that used but I cannot seem to find any relevant information :(.

**Comment by tamalsaha** [comment]
We have removed the extended api server in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0 . So, this should be fixed.
