### ISSUE TITLE
Feature request:  specify source namespaces via configuration (one or all)

### ISSUE THREAD

**Issue by gralfca** [appscode/kubed#355]
Sometimes it's useful to centralize the source of truth that nobody else can change. For instance, in a large kubernetes cluster you may want to share details about cluster resources that are not running in kubernetes. This global configuration (i.e. like docker-registry-secret, for instance) could be replicated from the "commonconfig" namespace or other namespace specified in the kubed config. In this case, we wouldn't replicate all annotated configmaps or secrets but instead only those that come from the configured namespace.  If no configured namespace  source is specified, the present behavior of replicating all annotated configmap/secret could be applied.

**Comment by kfox1111** [comment]
I have this same use case. I would like it to only look at a particular namespace to sync from. This would allow a much more secure cluster.
