### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by tamalsaha** [appscode/kubed#363]
Hello folks,
I am curious to understand what you are using kubed for?

- Take backup of cluster yamls?
- Sync secrets / configmaps?
- search your cluster?

When I started the project, I needed various individual tasks to be done. Instead of writing a separate tool for each one of them ( and filling up the cluster with operators and controllers), I created this project as a kitchen sink for all those tools that don't fit with anything else. I called the project `kube-DEE` as in Kubernetes Daemon. 

As things have progressed, there are various limitations to the original approach. One of the primary limitations is the rise of CRDs. This project needs to be re-written using dynamic clients to support CRDs that we can't know ahead of time.

The cluster backup option had its own limitations around how to clean up old backups. So, we introduced a plugin mechanism to our github.com/stashed project and added support cluster backup https://github.com/stashed/cluster (to be released soon). This uses restic.net under the hood for encrypted, deduplicated backups and uses restic's support for retention policy to clean up old backup.

Originally we needed some support to cleanup old data from InfluxDB (for monitoring) and Elasticsearch (for logging). I don't think InfluxDB is used much. And for Elasticsearch, you might even use curator.

We had some features around watching events. I think it is still useful. But I would probably want to pass the notifications to Prometheus Alertmanager and let it do the routing/silencing/alerting etc, if I were to do this today. Also, once the Kubernetes Dynamic Audit webhook hits beta, we probably should use that instead of the Lister/Watcher mechanism to generate events.

The search engine functionality is something we want to see. But it needs rework to ensure it supports any type of resource and CRDs and it enforces the AuthZ using SubjectReview apis.

The configmap and secret syncer feature is still useful.

So, can you please tell me how you are using this project and what do you want to see in future in addition to fixing this memory issue (which seems to be related to the https://github.com/appscode/kubed/pull/361 ).

**Comment by sebastiansirch** [comment]
We are using kubed solely for syncing configmaps and secrets (especially distributing TLS certificates for nginx ingress to all namespaces).

**Comment by scottrigby** [comment]
Same as @sebastiansirch

**Comment by discostur** [comment]
Using kubed in the same style as @sebastiansirch, we are syncing configmaps / secrets ( SSL Certificates ) across our namespaces.

**Comment by deini** [comment]
Same here, distributing TLS certificates for nginx ingress to all namespaces.

**Comment by alanjcastonguay** [comment]
Same as above. When wanting purely secret/configmap/etc replication/reflection across namespaces, the other features are a lot of unnecessary complexity. I wish this feature was in a standalone container without baggage, and the specification of what resources to copy was in a readable/diffable configmap/cr (or list of configmaps).

**Comment by sebastiansirch** [comment]
In the meanwhile, we (my company) built an operator solely for syncing config maps and secrets. The configuration, i.e. what to sync where, is stored in CRDs. If this sounds interesting, I can check whether we can make this publicly available as open source project.

**Comment by yoanisgil** [comment]
Same as @sebastiansirch. 

@sebastiansirch I would be more than happy to give it a try.

@tamalsaha  Thanks for all the good work!

**Comment by tamalsaha** [comment]
I took your feedback and reboot the project in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0 release. We have removed all the features except configuration syncer and added CI tests for various versions of Kubernetes. Thanks for trying Kubed.
