### ISSUE TITLE
Kubernetes 1.16 and "extensions/v1beta1"

### ISSUE THREAD

**Issue by ruzickap** [appscode/kubed#369]
Hello.

I'm trying to install `kubed` using Helm chart into k8s 1.16 and I'm getting this error:

```bash
$ helm install --dry-run --debug appscode/kubed --name kubed --version 0.11.0 --namespace kube-system --wait --set config.clusterName=my_k8s_cluster --set apiserver.enabled=false
[debug] Created tunnel using local port: '40423'

[debug] SERVER: "127.0.0.1:40423"

[debug] Original chart version: "0.11.0"
[debug] Fetched appscode/kubed to /home/pruzicka/.helm/cache/archive/kubed-v0.11.0.tgz

[debug] CHART PATH: /home/pruzicka/.helm/cache/archive/kubed-v0.11.0.tgz

Error: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

The problem is described here:
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/

The `extensions/v1beta1` was deprecated: https://github.com/appscode/kubed/blob/master/chart/kubed/templates/deployment.yaml#L1

Thanks for looking at it...

**Comment by IvanovOleg** [comment]
I have the same issue helm 3 / kubernetes 1.16.2

**Comment by donifer** [comment]
Also getting this with helm 3 / k8s 1.16.2, is there any workaround other than forking the chart?

**Comment by mmisztal1980** [comment]
the PR was merged but it seems that the fix has not been released yet - has it?

**Comment by msaurabhee** [comment]
@mmisztal1980 exactly my problem as well, I am forking the repo to use it.

**Comment by tamalsaha** [comment]
This should be fixed with the https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0 release.
