### ISSUE TITLE
Don't regenerate a certificate authority and a certificate everytime you deploy the helm chart

### ISSUE THREAD

**Issue by jurgenweber** [appscode/kubed#371]
https://github.com/appscode/kubed/blob/master/chart/kubed/templates/apiregistration.yaml#L1-L5

```
{{- $ca := genCA "ca" 3650 }}
{{- $cn := include "kubed.fullname" . -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $cert := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
```

Generated resources like the above are problematic when using tools like helmfile because on every application new certificates are generated and a release created with helm. This makes it slow and gives the user a false sense of a tool that is updated a lot for no reason.

While this is a great feature, I am not suggesting removing it but can a manual override be added so an administrator can statically set it and not have it generate all the time. Also If the apiserver is disabled is this certificate still required?

**Comment by tamalsaha** [comment]
Recently added a way to pass certificates from outside in one of our charts. https://github.com/kubevault/installer/commit/57d4945ff81a773ecd9775dd03b4605fc6bfe5cc#diff-31a50bdfee9401ac802054fe55e6602c

Does something like that solve your use-case?

> Also If the apiserver is disabled is this certificate still required?

This has been changed in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0 release.

**Comment by jurgenweber** [comment]
> Does something like that solve your use-case?

Yeah, it does.

> This has been changed in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0 release.

Great, thanks! Looking forward to the release!
