### ISSUE TITLE
Is there a reason why apiservice still exists?

### ISSUE THREAD

**Issue by rikatz** [appscode/kubed#408]
So I've been looking for something to simply synchronize secrets and configmaps across multiple clusters and found kubed :)

It seems very promising, and as I've seen the project has been rebooted to something simpler right?

So I've compiled the main program and it still tries to start an apiservice, but what I think is that (and according to the docs) now it's only a controller that could easily work without opening any port.

So, may the apiservice part be removed? I can go through this if desired :D

Thank you

**Comment by martaver** [comment]
Agreed... the api server seems to require certificates too, which if you let kubed helm chart generate them, will re-generate them constantly (a problem for terraform/pulumi). But if you turn off generating them, then now you have to issue your own certificates - why all that trouble if apiservice doesn't exist?
