### ISSUE TITLE
Cluster sync across AWS EKS clusters

### ISSUE THREAD

**Issue by jdepp** [appscode/kubed#434]
I'm running into an issue where I have 2 clusters on AWS EKS (AWS' managed Kubernetes service) and I cannot sync secrets from cluster A to cluster B. I'm able to successfully pass in my kubeconfig file via `config.kubeconfigContent`. Looking at the logs of the kubed pod, it's saying that the `aws` CLI is not found. The way that `kubectl` authenticates with AWS EKS is via AWS IAM roles and `aws-iam-authenticator` which I believe "under-the-hood" is using the `aws` CLI to authenticate `kubectl` with the cluster with the user's AWS creds that are stored locally.

Is there any workaround for this on the kubed side? This makes it seem as if kubed doesn't work with AWS EKS clusters because the kubeconfig file can't properly authenticate with them.

**Comment by Chili-Man** [comment]
You need to have either `aws-iam-authenticator` or `aws` cli tool installed locally into the same container that is running `kubed` in order to properly authenticate to the EKS clusters; which means you will need to build your own custom kubed image to add the authentication tools.

**Comment by jdepp** [comment]
Closed this issue. We made our own custom image with the AWS CLI installed which allowed us to be able to auth to our EKS clusters. Thanks for the tip!
